<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AgentAllowedFamilyTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('agent_allowed_family')->delete();
        
        \DB::table('agent_allowed_family')->insert(array (
            0 => 
            array (
                'id' => 1,
                'family' => 'Azureus 2.5.0.4',
                'start_name' => 'Azureus 2.5.0.4',
                'peer_id_pattern' => '/^-AZ2504-/',
                'peer_id_match_num' => 0,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-AZ2504-',
                'agent_pattern' => '/^Azureus 2.5.0.4/',
                'agent_match_num' => 0,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Azureus 2.5.0.4',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            1 => 
            array (
                'id' => 2,
                'family' => 'uTorrent 1.6.1',
                'start_name' => 'uTorrent 1.6.1',
                'peer_id_pattern' => '/^-UT1610-/',
                'peer_id_match_num' => 0,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-UT1610-',
                'agent_pattern' => '/^uTorrent\\/1610/',
                'agent_match_num' => 0,
                'agent_matchtype' => 'dec',
                'agent_start' => 'uTorrent/1610',
                'exception' => 'no',
                'allowhttps' => 'no',
                'comment' => '',
                'hits' => 0,
            ),
            2 => 
            array (
                'id' => 3,
                'family' => 'Bittorrent 6.x',
                'start_name' => 'Bittorrent 6.0.1',
            'peer_id_pattern' => '/^M6-([0-9])-([0-9])--/',
                'peer_id_match_num' => 2,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => 'M6-0-1--',
            'agent_pattern' => '/^BitTorrent\\/6([0-9])([0-9])([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'BitTorrent/6010',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            3 => 
            array (
                'id' => 4,
                'family' => 'Deluge 0.x',
                'start_name' => 'Deluge 0.5.8.9',
            'peer_id_pattern' => '/^-DE0([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-DE0589-',
            'agent_pattern' => '/^Deluge 0\\.([0-9])\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Deluge 0.5.8.9',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'family' => 'Transmission1.x',
            'start_name' => 'Transmission 1.06 (build 5136)',
            'peer_id_pattern' => '/^-TR1([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-TR1060-',
            'agent_pattern' => '/^Transmission\\/1\\.([0-9])([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Transmission/1.06',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            5 => 
            array (
                'id' => 6,
            'family' => 'RTorrent 0.x(with libtorrent 0.x)',
            'start_name' => 'rTorrent 0.8.0 (with libtorrent 0.12.0)',
            'peer_id_pattern' => '/^-lt([0-9A-E])([0-9A-E])([0-9A-E])([0-9A-E])-/',
                'peer_id_match_num' => 4,
                'peer_id_matchtype' => 'hex',
                'peer_id_start' => '-lt0C00-',
            'agent_pattern' => '/^rtorrent\\/0\\.([0-9])\\.([0-9])\\/0\\.([1-9][0-9]*)\\.(0|[1-9][0-9]*)/',
                'agent_match_num' => 4,
                'agent_matchtype' => 'dec',
                'agent_start' => 'rtorrent/0.8.0/0.12.0',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'family' => 'Rufus 0.x',
                'start_name' => 'Rufus 0.6.9',
                'peer_id_pattern' => '',
                'peer_id_match_num' => 0,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '',
            'agent_pattern' => '/^Rufus\\/0\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Rufus/0.6.9',
                'exception' => 'no',
                'allowhttps' => 'no',
                'comment' => '',
                'hits' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'family' => 'Azureus 3.x',
                'start_name' => 'Azureus 3.0.5.0',
            'peer_id_pattern' => '/^-AZ3([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-AZ3050-',
            'agent_pattern' => '/^Azureus 3\\.([0-9])\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Azureus 3.0.5.0',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'family' => 'uTorrent 1.7.x',
                'start_name' => 'uTorrent 1.7.5',
            'peer_id_pattern' => '/^-UT17([0-9])([0-9])-/',
                'peer_id_match_num' => 2,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-UT1750-',
            'agent_pattern' => '/^uTorrent\\/17([0-9])([0-9])/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
                'agent_start' => 'uTorrent/1750',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            9 => 
            array (
                'id' => 10,
                'family' => 'BitRocket 0.x',
            'start_name' => 'BitRocket 0.3.3(32)',
            'peer_id_pattern' => '/^-BR0([0-9])([1-9][0-9]*)-/',
                'peer_id_match_num' => 2,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-BR0332-',
            'agent_pattern' => '/^BitRocket\\/0\\.([0-9])\\.([0-9])\\(([1-9][0-9]*)\\) libtorrent\\/0\\.([1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)/',
                'agent_match_num' => 6,
                'agent_matchtype' => 'dec',
            'agent_start' => 'BitRocket/0.3.3(32) libtorrent/0.13.0.0',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'family' => 'MLDonkey 2.9.x',
                'start_name' => 'MLDonkey 2.9.2',
            'peer_id_pattern' => '/^-ML2\\.9\\.([0-9])-/',
                'peer_id_match_num' => 1,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-ML2.9.2-',
            'agent_pattern' => '/^MLDonkey\\/2\\.9\\.([0-9])/',
                'agent_match_num' => 1,
                'agent_matchtype' => 'dec',
                'agent_start' => 'MLDonkey/2.9.2',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'family' => 'uTorrent 1.8.x',
                'start_name' => 'uTorrent 1.8.0',
            'peer_id_pattern' => '/^-UT18([0-9])([0-9])-/',
                'peer_id_match_num' => 2,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-UT1800-',
            'agent_pattern' => '/^uTorrent\\/18([0-9])([0-9])/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
                'agent_start' => 'uTorrent/1800',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'family' => 'Azureus 4.x',
                'start_name' => 'Vuze 4.0.0.2',
            'peer_id_pattern' => '/^-AZ4([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-AZ4002-',
            'agent_pattern' => '/^Azureus 4\\.([0-9])\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Azureus 4.0.0.2',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'family' => 'SymTorrent',
                'start_name' => '',
                'peer_id_pattern' => '',
                'peer_id_match_num' => 0,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '',
                'agent_pattern' => '/^SymTorrent/',
                'agent_match_num' => 0,
                'agent_matchtype' => 'dec',
                'agent_start' => 'SymTorrent',
                'exception' => 'no',
                'allowhttps' => 'no',
                'comment' => '',
                'hits' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'family' => 'Deluge 1.x',
                'start_name' => 'Deluge 1.1.6',
            'peer_id_pattern' => '/^-DE1([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-DE1160-',
            'agent_pattern' => '/^Deluge 1\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Deluge 1.1.6',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            15 => 
            array (
                'id' => 16,
                'family' => 'uTorrent 1.8xB',
            'start_name' => 'uTorrent 1.80 Beta (build 9137)',
            'peer_id_pattern' => '/^-UT18([0-9])B-/',
                'peer_id_match_num' => 1,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-UT180B-',
            'agent_pattern' => '/^uTorrent\\/18([0-9])B\\(([1-9][0-9]*)\\)/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
            'agent_start' => 'uTorrent/180B(9137)',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'family' => 'uTorrent 2.x.x',
            'start_name' => 'uTorrent 2.0(build 17624)',
            'peer_id_pattern' => '/^-UT2([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-UT2000-',
            'agent_pattern' => '/^uTorrent\\/2([0-9])([0-9])([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'uTorrent/2000',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'family' => 'Transmission2.x',
                'start_name' => 'Transmission 2.0',
            'peer_id_pattern' => '/^-TR2([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-TR2000-',
            'agent_pattern' => '/^Transmission\\/2\\.([0-9])([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Transmission/2.00',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'family' => 'uTorrent 3.x',
                'start_name' => 'uTorrent/3000',
            'peer_id_pattern' => '/^-UT3([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-UT3000-',
            'agent_pattern' => '/^uTorrent\\/3([0-9])([0-9])([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'uTorrent/3000',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'family' => 'uTorrent 3.x',
                'start_name' => 'uTorrent',
                'peer_id_pattern' => '',
                'peer_id_match_num' => 0,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-UT355W-',
                'agent_pattern' => '/^uTorrent/',
                'agent_match_num' => 0,
                'agent_matchtype' => 'dec',
                'agent_start' => 'uTorrent',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'family' => 'Transmission3.x',
                'start_name' => 'Transmission 3.0',
            'peer_id_pattern' => '/^-TR3([0-9])([0-9])([0-9])-/',
                'peer_id_match_num' => 3,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-TR3000-',
            'agent_pattern' => '/^Transmission\\/3\\.([0-9])([0-9])/',
                'agent_match_num' => 3,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Transmission/3.00',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            21 => 
            array (
                'id' => 22,
                'family' => 'Deluge 2.x',
                'start_name' => 'Deluge 2.0.0',
            'peer_id_pattern' => '/^-DE2([0-9])([0-9])/',
                'peer_id_match_num' => 2,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-DE200',
            'agent_pattern' => '/^Deluge\\/2\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Deluge/2.0.0',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            22 => 
            array (
                'id' => 23,
                'family' => 'qBittorrent 4.x',
                'start_name' => 'qBittorrent 4.0.0',
            'peer_id_pattern' => '/^-qB4([0-9])([0-9])/',
                'peer_id_match_num' => 2,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-qB400',
            'agent_pattern' => '/^qBittorrent\\/4\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
                'agent_start' => 'qBittorrent/4.0.0',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'family' => 'Deluge 1.x',
                'start_name' => 'Deluge 1.0.0',
            'peer_id_pattern' => '/^-DE1([0-9])/',
                'peer_id_match_num' => 1,
                'peer_id_matchtype' => 'dec',
                'peer_id_start' => '-DE10',
            'agent_pattern' => '/^Deluge 1\\.([0-9])\\.([0-9])/',
                'agent_match_num' => 2,
                'agent_matchtype' => 'dec',
                'agent_start' => 'Deluge 1.0.0',
                'exception' => 'no',
                'allowhttps' => 'yes',
                'comment' => '',
                'hits' => 0,
            ),
        ));
        
        
    }
}