<?php

$lang_promotionlink = array
(
	'head_promotion_link' => "Promotion Link",
	'text_promotion_link' => "Promotion Link",
	'text_promotion_link_note_one' => "If you really like this site, why not help let more people know about it? You can do this by spreading out your promotion link. ",
	'text_promotion_link_note_two' => "Every user has an unique promotion link, a random URL generated by the system to identify him. When someone clicks on your promotion link, he will be redirected to this site and the system will reward you for helping spread the URL.",
	'text_you_would_get' => "You would get ",
	'text_bonus_points' => " bonus points each time your promotion link is clicked by an unrecorded IP. Only one click is counted in ",
	'text_seconds' => " seconds.",
	'text_your_promotion_link_is' => "Your promotion link: ",
	'text_promotion_link_note_four' => "You can choose anyway you like to use your promotion link. The following are some examples: ",
	'col_type' => "Type",
	'col_code' => "Code",
	'col_result' => "Result",
	'col_note' => "Note",
	'row_xhtml' => "XHTML 1.0",
	'text_xhtml_note' => "If you have your personal site, you can use XHTML code in your page.",
	'row_html' => "HTML 4.01",
	'text_html_note' => "If you have your personal site, you can use HTML code in your page.",
	'row_bbcode' => "BBCode",
	'text_bbcode_note' => "Most internet forums software (e.g. vBulletin, Discuz!, PHPWind) support BBCode. It's a good idea to put your promotion link in your signature.",
	'row_bbcode_userbar' => "BBCode userbar",
	'text_bbcode_userbar_note' => "Get your personal userbar. For userbar to work, you must <b>NOT</b> set your privacy level to 'strong' (at User CP).",
	'row_bbcode_userbar_alt' => "BBCode userbar alt.",
	'text_bbcode_userbar_alt_note' => "Use this if the above one doesn't work. For userbar to work, you must <b>NOT</b> set your privacy level to 'strong' (at User CP)."
)
?>
