<?php

namespace App\Http\Controllers\Legacy;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Nexus\Database\NexusDB;

/**
 * Replacement for `public/mybar.php` (deleted in the same PR).
 *
 * Phase 2 of the legacy migration — see `docs/legacy-strategy.md`
 * § "Phase 2" and `docs/migration-recipe.md`.
 *
 * The "userbar" PNG generator: a guest-reachable image endpoint
 * whose URL is embedded in user signatures across forums, snatch
 * pages, and the user-control-panel "userbar" snippet generated by
 * `App\Http\Controllers\Legacy\PromotionLinkController`. The
 * response is a 56×19 px GD-rendered PNG that overlays the user's
 * username, uploaded total, and downloaded total on top of one of
 * the background images shipped under
 * `public/pic/userbar/<bgpic>.png`.
 *
 * Original legacy flow (`public/mybar.php`, 150 LOC):
 *   1. `dbconn()` only — no `loggedinorreturn()`. The endpoint is
 *      reachable as a guest because forum signatures get rendered
 *      in pages/RSS feeds that may be crawled without a session.
 *   2. `intval($_GET['userid'])` and a `preg_match` on the request
 *      URI requiring a `userid=NNN.png` suffix. Both gates must
 *      pass — `userid=0` or a missing `.png` exits silently.
 *   3. Page-cache lookup keyed on the full request URI (so each
 *      colour/position permutation lands a separate cache row).
 *   4. SELECT username/uploaded/downloaded/class/privacy. Hidden
 *      when the user does not exist, has `privacy='strong'`, or has
 *      `class < $userbar_class` (configurable via
 *      `$AUTHORITY['userbar']`).
 *   5. GD pipeline: `imagecreatefrompng()` of the bg, then
 *      `imagestring()` of the username/up/down with caller-supplied
 *      RGB colours, font size, and x/y offsets. Each text block is
 *      gated on a `?no<name>=` flag.
 *   6. `imagepng()` to an output buffer, gzdeflate-cache the bytes
 *      for 5 minutes, then `header('Content-type: image/png')` +
 *      `echo gzinflate(...)`.
 *
 * Replacement contract:
 *   - Public route — same as the legacy script. Guests can hit it
 *     because forum signatures embed `<img src="/mybar.php?...">`.
 *   - URL preserved exactly (`/mybar.php?userid=NNN.png&bgpic=N&...`)
 *     so every existing signature `<img>` tag, every snippet stored
 *     on `users.promotion_link`, and the
 *     `PromotionLinkController` HTML output keep working without a
 *     template change.
 *   - The legacy regex requirement (`userid=NNN.png` literal in the
 *     request URI) is preserved bit-for-bit — see
 *     {@see hasPngSuffix()}. Without the `.png` literal the route
 *     returns a `204 No Content` (legacy returned an empty 200).
 *   - All four short-circuit gates (zero userid, missing .png suffix,
 *     unknown user, strong-privacy user, below-userbar-class user)
 *     return a 204 with an empty body. Same observable shape as the
 *     legacy `exit;` calls — the embedding `<img>` tag renders the
 *     browser's broken-image placeholder either way, but a 204
 *     spares the cache layer from caching a "successful" response.
 *   - All eighteen colour / position / size / suppress query
 *     parameters preserved, including the legacy bounds
 *     (`0..255` for RGB, `1..5` for size, `0..350` for x,
 *     `0..19` for y) and defaults.
 *   - Cache key matches the legacy `userbar_<requestUri>` shape.
 *
 * Sweep findings:
 *   - No `lang/<locale>/lang_mybar.php` files (the script never
 *     emitted localised text).
 *   - `App\Http\Controllers\Legacy\PromotionLinkController:126,129`
 *     emits `<img src=".../mybar.php?userid=N.png">` — kept intact,
 *     URL preserved.
 *   - No menu seeders / `Update.php` references — the page is an
 *     image endpoint, not a menu entry.
 */
class MyBarController extends Controller
{
    /**
     * Page-cache TTL for the gzdeflated PNG bytes. Mirrors the
     * legacy `$Cache->cache_value(..., 300)` value verbatim.
     */
    private const CACHE_TTL_SECONDS = 300;

    public function __invoke(Request $request): Response
    {
        $userId = (int) $request->query('userid', 0);
        if ($userId <= 0) {
            return $this->emptyResponse();
        }
        if (! self::hasPngSuffix((string) $request->server('REQUEST_URI', ''))) {
            return $this->emptyResponse();
        }

        $bgPic = (int) $request->query('bgpic', 0);

        $cacheKey = 'userbar_'.(string) $request->server('REQUEST_URI', '');
        $cached = $this->cacheGet($cacheKey);
        if ($cached !== null) {
            return $this->pngResponse($cached);
        }

        $row = NexusDB::table('users')
            ->where('id', $userId)
            ->select(['username', 'uploaded', 'downloaded', 'class', 'privacy'])
            ->first();
        $row = $row ? (array) $row : null;

        if ($row === null) {
            return $this->emptyResponse();
        }
        if (($row['privacy'] ?? '') === 'strong') {
            return $this->emptyResponse();
        }

        $userbarClass = (int) get_setting('authority.userbar');
        if ((int) $row['class'] < $userbarClass) {
            return $this->emptyResponse();
        }

        $bgPath = self::backgroundPath($bgPic);
        if ($bgPath === null) {
            return $this->emptyResponse();
        }

        $payload = $this->renderPng(
            backgroundPath: $bgPath,
            username: (string) $row['username'],
            uploaded: mksize((int) $row['uploaded']),
            downloaded: mksize((int) $row['downloaded']),
            request: $request,
        );
        if ($payload === null) {
            return $this->emptyResponse();
        }

        $deflated = gzdeflate($payload);
        if ($deflated === false) {
            // Cannot compress — serve the raw PNG without caching.
            return $this->pngResponse($payload);
        }

        $this->cachePut($cacheKey, $deflated);

        return $this->pngResponse($deflated);
    }

    /**
     * Mirror the legacy regex `/.*userid=([0-9]+)\.png$/i`. The
     * `.png` suffix is the marker forum signatures use to make the
     * URL look like an image to image-fetching crawlers and to most
     * browsers' Save-As menu.
     */
    private static function hasPngSuffix(string $requestUri): bool
    {
        return (bool) preg_match('/.*userid=([0-9]+)\.png$/i', $requestUri);
    }

    /**
     * Resolve the background image path. The legacy script used
     * `getFullDirectory('public/pic/userbar/<bgpic>.png')` which is
     * `realpath(...)` — we use Laravel's `public_path()` and
     * `realpath()` to ensure the resolved path stays inside the
     * userbar directory (defence against `..` traversal in the
     * `?bgpic=` parameter, even though `intval()` already
     * neutralises non-integer payloads).
     */
    private static function backgroundPath(int $bgPic): ?string
    {
        if ($bgPic < 0) {
            return null;
        }
        $candidate = public_path('pic/userbar/'.$bgPic.'.png');
        $real = realpath($candidate);
        if ($real === false) {
            return null;
        }
        $expectedRoot = realpath(public_path('pic/userbar')) ?: '';
        if ($expectedRoot === '' || ! str_starts_with($real, $expectedRoot.DIRECTORY_SEPARATOR)) {
            return null;
        }

        return $real;
    }

    /**
     * Drive GD to render the userbar overlay. Returns the raw PNG
     * bytes, or null on any failure path. Mirrors the legacy
     * `imagecreatefrompng` + `imagealphablending(false)` + three
     * `imagestring()` calls + `imagepng()` to an `ob_start()` buffer.
     */
    private function renderPng(
        string $backgroundPath,
        string $username,
        string $uploaded,
        string $downloaded,
        Request $request,
    ): ?string {
        $img = @imagecreatefrompng($backgroundPath);
        if ($img === false) {
            return null;
        }
        imagealphablending($img, false);

        if (! $request->query->has('noname')) {
            $this->stamp(
                $img,
                $username,
                $request,
                redKey: 'namered', defaultRed: 255,
                greenKey: 'namegreen', defaultGreen: 255,
                blueKey: 'nameblue', defaultBlue: 255,
                sizeKey: 'namesize', defaultSize: 3,
                xKey: 'namex', defaultX: 10,
                yKey: 'namey', defaultY: 3,
            );
        }
        if (! $request->query->has('noup')) {
            $this->stamp(
                $img,
                $uploaded,
                $request,
                redKey: 'upred', defaultRed: 0,
                greenKey: 'upgreen', defaultGreen: 255,
                blueKey: 'upblue', defaultBlue: 0,
                sizeKey: 'upsize', defaultSize: 3,
                xKey: 'upx', defaultX: 100,
                yKey: 'upy', defaultY: 3,
            );
        }
        if (! $request->query->has('nodown')) {
            $this->stamp(
                $img,
                $downloaded,
                $request,
                redKey: 'downred', defaultRed: 255,
                greenKey: 'downgreen', defaultGreen: 0,
                blueKey: 'downblue', defaultBlue: 0,
                sizeKey: 'downsize', defaultSize: 3,
                xKey: 'downx', defaultX: 180,
                yKey: 'downy', defaultY: 3,
            );
        }

        imagesavealpha($img, true);
        ob_start();
        imagepng($img);
        $bytes = (string) ob_get_clean();
        imagedestroy($img);

        return $bytes !== '' ? $bytes : null;
    }

    /**
     * Render one text block. Pulls colour / size / position from the
     * query string with the legacy bounds and defaults.
     *
     * @param  resource|\GdImage  $img
     */
    private function stamp(
        $img,
        string $text,
        Request $request,
        string $redKey,
        int $defaultRed,
        string $greenKey,
        int $defaultGreen,
        string $blueKey,
        int $defaultBlue,
        string $sizeKey,
        int $defaultSize,
        string $xKey,
        int $defaultX,
        string $yKey,
        int $defaultY,
    ): void {
        $red = self::intInRange($request, $redKey, $defaultRed, 0, 255);
        $green = self::intInRange($request, $greenKey, $defaultGreen, 0, 255);
        $blue = self::intInRange($request, $blueKey, $defaultBlue, 0, 255);
        $size = self::intInRange($request, $sizeKey, $defaultSize, 1, 5);
        $x = self::intInRange($request, $xKey, $defaultX, 0, 350);
        $y = self::intInRange($request, $yKey, $defaultY, 0, 19);

        $colour = imagecolorallocate($img, $red, $green, $blue);
        imagestring($img, $size, $x, $y, $text, $colour);
    }

    /**
     * Read a query-string integer and clamp it into `[$min, $max]`.
     * Mirrors the legacy ladder of `if (isset($_GET[k]) && k >= MIN
     * && k <= MAX) { intval(k) } else { default }` — including the
     * legacy "fall back to default when missing" semantics so a
     * URL without the parameter renders the same colour as before.
     */
    private static function intInRange(Request $request, string $key, int $default, int $min, int $max): int
    {
        if (! $request->query->has($key)) {
            return $default;
        }
        $raw = $request->query($key);
        if (! is_numeric($raw)) {
            return $default;
        }
        $value = (int) $raw;
        if ($value < $min || $value > $max) {
            return $default;
        }

        return $value;
    }

    /**
     * Empty-body response used for every short-circuit branch
     * (missing/zero userid, missing .png suffix, unknown user,
     * strong-privacy user, below-userbar-class user, GD failure).
     * Returns 204 so the cache layer sees an explicit "no content"
     * marker instead of caching a "successful" empty 200.
     */
    private function emptyResponse(): Response
    {
        return new Response('', Response::HTTP_NO_CONTENT);
    }

    /**
     * Wrap the (possibly gzdeflated) PNG bytes in a `Content-Type:
     * image/png` response. The legacy script always served the
     * deflated bytes after `gzinflate(...)`; we run the same
     * decompression here so the cached value can stay deflated.
     */
    private function pngResponse(string $payload): Response
    {
        $isDeflated = $this->looksDeflated($payload);
        $body = $isDeflated ? (string) @gzinflate($payload) : $payload;

        return new Response($body, Response::HTTP_OK, [
            'Content-Type' => 'image/png',
        ]);
    }

    /**
     * Cheap PNG-magic-bytes check. Raw PNG bytes always start with
     * `\x89PNG\r\n\x1a\n`; gzdeflated bytes never do.
     */
    private function looksDeflated(string $payload): bool
    {
        return ! str_starts_with($payload, "\x89PNG");
    }

    /**
     * Page-cache shim. Prefer the legacy `$Cache` global when
     * available (mirrors the contract `mybar.php` legacy script
     * relied on); fall back to the modern `NexusDB::cache_get`
     * helper so a caller that hasn't bootstrapped `include/core.php`
     * still hits the same Redis store.
     */
    private function cacheGet(string $key): ?string
    {
        $cache = $GLOBALS['Cache'] ?? null;
        if (is_object($cache) && method_exists($cache, 'get_value')) {
            $value = $cache->get_value($key);

            return is_string($value) && $value !== '' ? $value : null;
        }
        $value = NexusDB::cache_get($key);

        return is_string($value) && $value !== '' ? $value : null;
    }

    private function cachePut(string $key, string $value): void
    {
        $cache = $GLOBALS['Cache'] ?? null;
        if (is_object($cache) && method_exists($cache, 'cache_value')) {
            $cache->cache_value($key, $value, self::CACHE_TTL_SECONDS);

            return;
        }
        NexusDB::cache_put($key, $value, self::CACHE_TTL_SECONDS);
    }
}
